run:
  deadline: 2m

  # Include test files or not.
  # Default: true
  tests: false

linters:
  disable-all: true
  enable:
    - misspell
    - govet
    - staticcheck
    - errcheck
    - unparam
    - ineffassign
    - nakedret
    - gocyclo
    - dupl
    - goimports
    - revive
    - gosec
    - gosimple
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 600