name: Bug Report
description: Tell us about a problem you are experiencing
labels: [bug, triage]
assignees:
  - shipengqi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please fill the form below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: How can we reproduce this?
      description: Please share a public repository that reproduces the issue, or an example config file.
    validations:
      required: true
  - type: textarea
    id: kube-version
    attributes:
      label: kube version
      render: bash
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: OS
      description: "e.g. from `/etc/os-release`"
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I did search for other open and closed issues before opening this
          required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add
    validations:
      required: false