name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.goreleaser.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.goreleaser.yaml'

jobs:
  # Run E2E test against all kubernetes versions on kind
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - 1.29.0
          - 1.30.0
          - 1.31.0
          - 1.32.0
          - 1.33.0
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.12.0
      - name: Prepare
        run: kubectl apply -f testdata/nginx.yaml
      - name: Readiness
        run: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app=nginx --timeout=500s
      - run: go test -v -coverprofile=coverage.out .
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          files: coverage.out
