name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Run E2E test against all kubernetes versions on kind
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - 1.24.0
          - 1.25.0
          - 1.26.0
          - 1.27.0
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: helm/kind-action@v1.5.0
      - run: go test -v -coverprofile=coverage.out .
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
          files: coverage.out
